<a href="https://colab.research.google.com/github/cda79/461-lab01-introduction/blob/main/IAT461_LabTask01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🧪 Week 1 - Lab Task: Working with DataFrames and Arrays #

**🎯 Objective**

Explore and manipulate data by using Pandas and NumPy.

### Dataset ###
Use the Titanic dataset, available from the official Pandas documentation repository.

🔗 Dataset URL:
https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv

📥 Instruction:
Load the dataset directly into a DataFrame from the URL:

In [202]:
import numpy as np
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv")

### Part 1: Data Exploration ###
1. Print the shape and column names of the dataset.

2. Display basic information and summary statistics about the dataset.

3. Show the first 10 rows.

In [203]:
# 1. Print the shape and column names of the dataset.
dataNumpy = np.array(df)
print(f'Shape of dataset (rows, columns): {dataNumpy.shape}')
print(f'All column names:{list(df)}')

print()

# 2. Display basic information and summary statistics about the dataset.
print('Summary:')
print(df.info())

print()

print('Basic Information:')
print(df.describe())

print()

#3. Show first 10 rows
print('First Ten Rows:')
df.head(10)

Shape of dataset (rows, columns): (891, 12)
All column names:['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

Summary:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None

Basic Information:
       PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000
mean    446.000000    0.383838    2.308642   29.699118    0.523008
std     257.353842    0.486592    0.836071   14.526497    1.102743
min       1.000000    0.000000    1.000000    0.420000    0.000000
25%     223.500000    0.000000    2.000000   20.125000    0.000000
50%     446.000000    0.000000    3.000000   28.000000    0.000000
75%     668.500000    1.000000    3.000000   38.000000    1.000000
max     891.000000    1.000000    3.000000   80.000000    8.000000

            Parch        Fare
count  891.000000  891.000000
mean     0.381594   32.204208
std      0.806057   49.693429
min      0.000000    0.000000
25%      0.000000    7.910400
50%      0.000000   14.454200
75%      0.000000   31.000000
max      6.000000  512.329200

First Ten Rows:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

### Part 2: Indexing and Selection ###
1. Select the names column.

2. Select multiple columns of your choice.

3. Select a single row from the dataset.

4. Select a rectangular section (subset of rows and columns).

In [204]:
# 1. Select the names column
name_data = df['Name']
name_data.head()

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                Heikkinen, Miss Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: object

In [205]:
# 2. Multiple columns of my choice
age_sex = df[["Age", "Sex"]]
age_sex.head()

    Age     Sex
0  22.0    male
1  38.0  female
2  26.0  female
3  35.0  female
4  35.0    male

In [206]:
# 3. Select a single row from the dataset.
df.iloc[[1]]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [207]:
# 4. Select a rectangular section (subset of rows and columns).
young_passengers_basic = df.loc[df["Age"] < 35, ["Name", "Sex", "Age"]]
young_passengers_basic.head()

                                                Name     Sex   Age
0                            Braund, Mr. Owen Harris    male  22.0
2                              Heikkinen, Miss Laina  female  26.0
7                      Palsson, Master Gosta Leonard    male   2.0
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0

### Part 3: Filtering ###

1. Show only the rows where the age is above 60.

2. Show rows where the fare is above 100 and the passenger was in 1st class.

3. Identify and isolate rows with missing values in the age column.

In [208]:
# 1. Show only the rows where the age is above 60.
old_passengers = df.loc[df["Age"] > 60]
old_passengers.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
170,171,0,1,"Van der hoef, Mr. Wyckoff",male,61.0,0,0,111240,33.5000,B19,S

In [209]:
# 2. Show rows where the fare is above 100 and the passenger was in 1st class.
expensive_passengers = df.loc[(df["Fare"] > 100) & (df["Pclass"] == 1)]
expensive_passengers.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
88,89,1,1,"Fortune, Miss Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.0,0,1,PC 17558,247.5208,B58 B60,C
195,196,1,1,"Lurette, Miss Elise",female,58.0,0,0,PC 17569,146.5208,B80,C

In [210]:
# 3. Identify and isolate rows with missing values in the age column.
age_na = df[(df["Age"].isna() & df["Age"].isnull())]
age_na.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q

### Part 4: Reindexing and Dropping ###

1. Reverse the row order of the dataset.

2. Remove one column from the dataset.

3. Remove all rows with missing values in the age column.

In [211]:
# 1. Reverse the row order of the dataset.
df_reversed = df.iloc[::-1]
df_reversed.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S

In [212]:
# 2. Remove one column from the dataset.
df_column_removed = df.drop(columns='Sex')
df_column_removed.head()

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,NaN,S

In [213]:
# 3. Remove all rows with missing values in the age column.
df_age_clean = df.dropna(subset=['Age'])
df_age_clean.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S

### Part 5: Arithmetic and Data Alignment ###

1. Create a new column that converts fares from USD to Euros.

2. Subtract the average age from every age value.

3. Subtract a custom array from two selected columns in the dataset.

In [214]:
# 1. Create a new column that converts fares from USD to Euros.
eur_rate = .86018
df['Fare_EUR'] = df['Fare'] * eur_rate
print(df[['Fare', 'Fare_EUR']].head())

print()

# 2. Subtract the average age from every age value.
print('Age BEFORE subtraction:')
print(df[['Age']].head())
print()

print('Age AFTER subtraction:')
avg_age = df['Age'].mean()

df_age = df.copy()
df_age['Age'] = df['Age'] - avg_age
print(df_age[['Age']].head())

print()

# 3. Subtract a custom array from two selected columns in the dataset.
# each column has 891 values - generate a random numpy array of random integers going from 0-10 until n=891
custom_array =  np.random.randint(0, 10, size=891)
df_custom = pd.DataFrame(custom_array)

df_custom_array = df.copy()
df_custom_array[['Fare', 'Age']] = df[['Fare', 'Age']].sub(custom_array, axis=0)

print('Custom Array:')
print(df_custom.head())
print()
print('Fare and Age BEFORE custom subtraction:')
print(df[['Fare', 'Age']].head())
print()
print('Fare and Age AFTER custom subtraction:')
print(df_custom_array[['Fare', 'Age']].head())

      Fare   Fare_EUR
0   7.2500   6.236305
1  71.2833  61.316469
2   7.9250   6.816926
3  53.1000  45.675558
4   8.0500   6.924449

Age BEFORE subtraction:
    Age
0  22.0
1  38.0
2  26.0
3  35.0
4  35.0

Age AFTER subtraction:
        Age
0 -7.699118
1  8.300882
2 -3.699118
3  5.300882
4  5.300882

Custom Array:
   0
0  4
1  5
2  1
3  6
4  6

Fare and Age BEFORE custom subtraction:
      Fare   Age
0   7.2500  22.0
1  71.2833  38.0
2   7.9250  26.0
3  53.1000  35.0
4   8.0500  35.0

Fare and Age AFTER custom subtraction:
      Fare   Age
0   3.2500  18.0
1  66.2833  33.0
2   6.9250  25.0
3  47.1000  29.0
4   2.0500  29.0

### Part 6: Applying Functions ###

1. Create a new column with the number of characters in each name.

2. Calculate the difference between fare and age for each row.

3. Round all numerical values in the dataset to one decimal place.

In [215]:
#1. Create a new column with the number of characters in each name.
df['Name_length'] = df['Name'].str.len()
print(df[['Name', 'Name_length']].head())

print()
#2. Calculate the difference between fare and age for each row.
df['fare_age_diff'] = df['Fare'] - df['Age']
print(df[['Fare', 'Age', 'fare_age_diff']].head())

print()

#3. Round all numerical values in the dataset to one decimal place.
df_onedecimal = df.round(1)
print('Round numerical values to 1 decimal place:')
print(df[['PassengerId','Survived','Pclass','Age','Fare']].head())
print(df_onedecimal[['PassengerId','Survived','Pclass','Age','Fare']].head())

                                                Name  Name_length
0                            Braund, Mr. Owen Harris           23
1  Cumings, Mrs. John Bradley (Florence Briggs Th...           51
2                              Heikkinen, Miss Laina           21
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)           44
4                           Allen, Mr. William Henry           24

      Fare   Age  fare_age_diff
0   7.2500  22.0       -14.7500
1  71.2833  38.0        33.2833
2   7.9250  26.0       -18.0750
3  53.1000  35.0        18.1000
4   8.0500  35.0       -26.9500

Round numerical values to 1 decimal place:
   PassengerId  Survived  Pclass   Age     Fare
0            1         0       3  22.0   7.2500
1            2         1       1  38.0  71.2833
2            3         1       3  26.0   7.9250
3            4         1       1  35.0  53.1000
4            5         0       3  35.0   8.0500
   PassengerId  Survived  Pclass   Age  Fare
0            1         0       3  22.0   7.2
1            2         1       1  38.0  71.3
2            3         1       3  26.0   7.9
3            4         1       1  35.0  53.1
4            5         0       3  35.0   8.0

### Part 7: Mapping and Transformation ###
1. Convert categorical values in the gender column to numeric codes.

2. Create a new column that categorizes age into groups (e.g., child, adult, senior).

In [216]:
# 1. Convert categorical values in the gender column to numeric codes.
df["Sex_number"] = df["Sex"].replace({"male": "0", "female": "1"})
print(df[['Sex_number','Sex']].head())
print()

# 2. Create a new column that categorizes age into groups (e.g., child, adult, senior).
bins = [0, 12, 19, 64, 100]
labels = ['Child', 'Teenager', 'Adult', 'Senior']
df['Age_group'] = pd.cut(df['Age'], bins=bins, labels=labels)
print(df[['Age', 'Age_group']].head(30))

  Sex_number     Sex
0          0    male
1          1  female
2          1  female
3          1  female
4          0    male

     Age Age_group
0   22.0     Adult
1   38.0     Adult
2   26.0     Adult
3   35.0     Adult
4   35.0     Adult
5    NaN       NaN
6   54.0     Adult
7    2.0     Child
8   27.0     Adult
9   14.0  Teenager
10   4.0     Child
11  58.0     Adult
12  20.0     Adult
13  39.0     Adult
14  14.0  Teenager
15  55.0     Adult
16   2.0     Child
17   NaN       NaN
18  31.0     Adult
19   NaN       NaN
20  35.0     Adult
21  34.0     Adult
22  15.0  Teenager
23  28.0     Adult
24   8.0     Child
25  38.0     Adult
26   NaN       NaN
27  19.0  Teenager
28   NaN       NaN
29   NaN       NaN